SAP_GCL/SAP_GCL/Models/GoodMovement.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace SAP_GCL.Models
{
    public class GoodMovement
    {
        public int ID { get; set; }
        [MaxLength(50), Display(Name = "Posting Date")]
        public string pstng_date { get; set; }
        [MaxLength(12), Display(Name = "Document Date")]
        public string doc_date { get; set; }
        [MaxLength(12), Display(Name = "Username")]
        public string pr_uname { get; set; }
        [MaxLength(50), Display(Name = "Reference Document")]
        public string ref_doc_no { get; set; }
        [MaxLength(50), Display(Name = "Material")]
        public string material { get; set; }
        [MaxLength(5), Display(Name = "Plant")]
        public string plant { get; set; }
        [MaxLength(6), Display(Name = "Storage Location")]
        public string stge_loc { get; set; }
        [MaxLength(4), Display(Name = "Movement Type")]
        public string move_type { get; set; }
        [MaxLength(15), Display(Name = "Purchase Order Number")]
        public string po_number { get; set; }
        [MaxLength(5), Display(Name = "Purchase Order Item")]
        public string po_item { get; set; }
        [MaxLength(10), Display(Name = "Quantity")]
        public double entry_qnt { get; set; }
        [MaxLength(10), Display(Name = "Unit of Measure")]
        public string entry_uom { get; set; }
        [MaxLength(5), Display(Name = "Movement Indicator")]
        public string mvt_ind { get; set; }
        [MaxLength(5)]
        public string gm_code { get; set; }
        [MaxLength(15)]
        public double SAP_quantity { get; set; }

        [MaxLength(15)]
        public string move_reas { get; set; }
        public int Changed_Quantity { get; set; }
        public double Changed_Weight { get; set; }
        public string ReasonForChange { get; set; }
        public string ChangedBy { get; set; }

    }
}

SAP_GCL/SAP_GCL/Controllers/GoodMovementsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SAP_GCL.Models;

namespace SAP_GCL.Controllers
{
    public class GoodMovementsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        
        // GET: GoodMovements
        public ActionResult Index()
        {
            var model = new GoodMovementSelectionViewModel();
            foreach (var goodMovement in db.GoodMovement)
            {
                var editorViewModel = new SelectGoodMovementEditorViewModel()
                {
                    ID = goodMovement.ID,
                    ChangedBy = goodMovement.ChangedBy,
                    Changed_Quantity = goodMovement.Changed_Quantity,
                    Changed_Weight = goodMovement.Changed_Weight,
                    doc_date = goodMovement.doc_date,
                    entry_qnt = goodMovement.entry_qnt,
                    entry_uom = goodMovement.entry_uom,
                    gm_code = goodMovement.gm_code,
                    material = goodMovement.material,
                    move_reas = goodMovement.move_reas,
                    move_type = goodMovement.move_type,
                    mvt_ind = goodMovement.mvt_ind,
                    plant = goodMovement.plant,
                    po_item = goodMovement.po_item,
                    po_number = goodMovement.po_number,
                    pr_uname = goodMovement.pr_uname,
                    pstng_date = goodMovement.pstng_date,
                    ReasonForChange = goodMovement.ReasonForChange,
                    ref_doc_no = goodMovement.ref_doc_no,
                    SAP_quantity = goodMovement.SAP_quantity,
                    stge_loc = goodMovement.stge_loc,
                    Selected = true
                };
                model.GoodMovements.Add(editorViewModel);
            }
            return View(model);
        }

        [HttpPost]
        public ActionResult SubmitSelected(GoodMovementSelectionViewModel model)
        {
            // get the ids of the items selected:
            var selectedIds = model.getSelectedIds();
            // Use the ids to retrieve the records for the selected people
            // from the database:
            var selectedGoodsMovement = from x in db.GoodMovement
                                 where selectedIds.Contains(x.ID)
                                 select x;
            // Process according to your requirements:
           /* foreach (var person in selectedPeople)
            {
                System.Diagnostics.Debug.WriteLine(
                    string.Format("{0} {1}", person.firstName, person.LastName));
            }*/
            // Redirect somewhere meaningful (probably to somewhere showing 
            // the results of your processing):
            return RedirectToAction("Index");
        }

        // GET: GoodMovements/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GoodMovement goodMovement = db.GoodMovement.Find(id);
            if (goodMovement == null)
            {
                return HttpNotFound();
            }
            return View(goodMovement);
        }

        // GET: GoodMovements/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: GoodMovements/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,pstng_date,doc_date,pr_uname,ref_doc_no,material,plant,stge_loc,move_type,po_number,po_item,entry_qnt,entry_uom,ref_doc,prod_date,mvt_ind,gm_code,SAP_quantity,move_reas")] GoodMovement goodMovement)
        {
            if (ModelState.IsValid)
            {
                db.GoodMovement.Add(goodMovement);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(goodMovement);
        }

        // GET: GoodMovements/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GoodMovement goodMovement = db.GoodMovement.Find(id);
            if (goodMovement == null)
            {
                return HttpNotFound();
            }
            return View(goodMovement);
        }

        // POST: GoodMovements/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,pstng_date,doc_date,pr_uname,ref_doc_no,material,plant,stge_loc,move_type,po_number,po_item,entry_qnt,entry_uom,ref_doc,prod_date,mvt_ind,gm_code,SAP_quantity,move_reas")] GoodMovement goodMovement)
        {
            if (ModelState.IsValid)
            {
                db.Entry(goodMovement).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(goodMovement);
        }

        // GET: GoodMovements/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GoodMovement goodMovement = db.GoodMovement.Find(id);
            if (goodMovement == null)
            {
                return HttpNotFound();
            }
            return View(goodMovement);
        }

        // POST: GoodMovements/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            GoodMovement goodMovement = db.GoodMovement.Find(id);
            db.GoodMovement.Remove(goodMovement);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SAP_GCL/SAP_GCL/Views/GoodMovements/Index.cshtml
@model SAP_GCL.Models.GoodMovementSelectionViewModel

@{
    ViewBag.Title = "Index";
}

<div class="page-content-wrapper">
    <!-- BEGIN CONTENT BODY -->
    <div class="page-content">
        <!-- BEGIN PAGE HEADER-->
        <!-- BEGIN THEME PANEL -->
        <div class="theme-panel hidden-xs hidden-sm">
            <div class="toggler"> </div>
            <div class="toggler-close"> </div>
            <div class="theme-options">
                <div class="theme-option theme-colors clearfix">
                    <span> THEME COLOR </span>
                    <ul>
                        <li class="color-default current tooltips" data-style="default" data-container="body" data-original-title="Default"> </li>
                        <li class="color-darkblue tooltips" data-style="darkblue" data-container="body" data-original-title="Dark Blue"> </li>
                        <li class="color-blue tooltips" data-style="blue" data-container="body" data-original-title="Blue"> </li>
                        <li class="color-grey tooltips" data-style="grey" data-container="body" data-original-title="Grey"> </li>
                        <li class="color-light tooltips" data-style="light" data-container="body" data-original-title="Light"> </li>
                        <li class="color-light2 tooltips" data-style="light2" data-container="body" data-html="true" data-original-title="Light 2"> </li>
                    </ul>
                </div>
                <div class="theme-option">
                    <span> Theme Style </span>
                    <select class="layout-style-option form-control input-sm">
                        <option value="square" selected="selected">Square corners</option>
                        <option value="rounded">Rounded corners</option>
                    </select>
                </div>
                <div class="theme-option">
                    <span> Layout </span>
                    <select class="layout-option form-control input-sm">
                        <option value="fluid" selected="selected">Fluid</option>
                        <option value="boxed">Boxed</option>
                    </select>
                </div>
                <div class="theme-option">
                    <span> Header </span>
                    <select class="page-header-option form-control input-sm">
                        <option value="fixed" selected="selected">Fixed</option>
                        <option value="default">Default</option>
                    </select>
                </div>
                <div class="theme-option">
                    <span> Top Menu Dropdown</span>
                    <select class="page-header-top-dropdown-style-option form-control input-sm">
                        <option value="light" selected="selected">Light</option>
                        <option value="dark">Dark</option>
                    </select>
                </div>
                <div class="theme-option">
                    <span> Sidebar Mode</span>
                    <select class="sidebar-option form-control input-sm">
                        <option value="fixed">Fixed</option>
                        <option value="default" selected="selected">Default</option>
                    </select>
                </div>
                <div class="theme-option">
                    <span> Sidebar Menu </span>
                    <select class="sidebar-menu-option form-control input-sm">
                        <option value="accordion" selected="selected">Accordion</option>
                        <option value="hover">Hover</option>
                    </select>
                </div>
                <div class="theme-option">
                    <span> Sidebar Style </span>
                    <select class="sidebar-style-option form-control input-sm">
                        <option value="default" selected="selected">Default</option>
                        <option value="light">Light</option>
                    </select>
                </div>
                <div class="theme-option">
                    <span> Sidebar Position </span>
                    <select class="sidebar-pos-option form-control input-sm">
                        <option value="left" selected="selected">Left</option>
                        <option value="right">Right</option>
                    </select>
                </div>
                <div class="theme-option">
                    <span> Footer </span>
                    <select class="page-footer-option form-control input-sm">
                        <option value="fixed">Fixed</option>
                        <option value="default" selected="selected">Default</option>
                    </select>
                </div>
            </div>
        </div>
        <!-- END THEME PANEL -->
        <!-- BEGIN PAGE BAR -->
        <div class="page-bar">
            <ul class="page-breadcrumb">
                <li>
                    <a href="index.html">Home</a>
                    <i class="fa fa-circle"></i>
                </li>
                <li>
                    <a href="#">Goods Receipt Note</a>
                    <i class="fa fa-circle"></i>
                </li>
                <li>
                    <span>WeighBridge Measurement</span>
                </li>
            </ul>
            <div class="page-toolbar">
                <div class="btn-group pull-right">
                    <button type="button" class="btn green btn-sm btn-outline dropdown-toggle" data-toggle="dropdown">
                        Actions
                        <i class="fa fa-angle-down"></i>
                    </button>
                    <ul class="dropdown-menu pull-right" role="menu">
                        <li>
                            <a href="#">
                                <i class="icon-bell"></i> Action
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <i class="icon-shield"></i> Another action
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <i class="icon-user"></i> Something else here
                            </a>
                        </li>
                        <li class="divider"> </li>
                        <li>
                            <a href="#">
                                <i class="icon-bag"></i> Separated link
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <!-- END PAGE BAR -->
        <!-- BEGIN PAGE TITLE-->
        <h1 class="page-title">
            WeighBridge Goods Receipt
            <small>These are list of Weighbridge measurement that has not been loaded in SAP</small>
        </h1>
        <!-- END PAGE TITLE-->
        <!-- END PAGE HEADER-->
        <div class="row">
            <div class="col-md-12">
                <!-- BEGIN EXAMPLE TABLE PORTLET-->
                <div class="portlet light bordered">
                    <div class="portlet-title">
                        <div class="caption font-dark">
                            <i class="icon-settings font-dark"></i>
                            <span class="caption-subject bold uppercase"> Weighbridge Goods Receipt</span>
                        </div>

                    </div>
                    <div class="portlet-body">
                        <div class="table-toolbar">
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="btn-group">

                                        <a title="Load Goods Reciept" id="sample_editable_1_new" href="@Url.Action("Load", "GoodRecieptNotes")" class="btn sbold green"><i class='fa fa-plus'></i> Load GRN</a>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="btn-group pull-right">
                                        <button class="btn green  btn-outline dropdown-toggle" data-toggle="dropdown">
                                            Tools
                                            <i class="fa fa-angle-down"></i>
                                        </button>
                                        <ul class="dropdown-menu pull-right">
                                            <li>
                                                <a href="javascript:;">
                                                    <i class="fa fa-print"></i> Print
                                                </a>
                                            </li>
                                            <li>
                                                <a href="javascript:;">
                                                    <i class="fa fa-file-pdf-o"></i> Save as PDF
                                                </a>
                                            </li>
                                            <li>
                                                <a href="javascript:;">
                                                    <i class="fa fa-file-excel-o"></i> Export to Excel
                                                </a>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
@using (Html.BeginForm("SubmitSelected", "GoodMovements", FormMethod.Post, new { encType = "multipart/form-data", name = "myform" }))
{
                        <table class="table table-striped table-bordered table-hover table-checkable order-column" id="sample_1">
                            <thead>
                                <tr>
                                    <th>
                                        <label class="mt-checkbox mt-checkbox-single mt-checkbox-outline">
                                            <input type="checkbox" class="group-checkable" data-set="#sample_1 .checkboxes" />
                                            <span></span>
                                        </label>
                                    </th>
                                    <th> Slip Date </th>
                                    <th> Reference </th>
                                    <th> Material </th>
                                    <th> Plant </th>
                                    <th> SLOC </th>
                                    <th>Document No </th>
                                    <th> WB QTY </th>
                                    <th> SAP QTY </th>
                                    <th>Status</th>
                                    <th>  </th>
                                </tr>
                            </thead>
                            <tbody>
                                @Html.EditorFor(model => model.GoodMovements)
                            </tbody>
                        </table>

                        <hr />
                        <br />
                        <input type="submit" name="operation" id="submit" value="Submit Selected" />
}
                    </div>
                </div>
                <!-- END EXAMPLE TABLE PORTLET-->
            </div>
        </div>
    </div>
    <!-- END CONTENT BODY -->
</div>
<!-- END CONTENT -->